// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FieldDef = { name: string, label: string, field_type: string, formula: string | null, };
