// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IncidentData = { medical_treatment: boolean, loss_of_consciousness: boolean, days_away: number, restricted_days: number, death: boolean, };
