// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldDef } from "./FieldDef";

export type ModuleBlueprint = { name: string, fields: Array<FieldDef>, };
